# Use an official Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy  requirements.txt from your project folder to app folder in the container
COPY requirements.txt .

# Install pip requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your app to /app directory
COPY . .

# Expose port (FastAPI usually runs on 8000)
EXPOSE 8000

# Start the FastAPI server using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
